name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      # Use the relative path from the repository root
      working-directory: ./src/main/docker
      run: docker build . --file Dockerfile.jvm --tag banking-service:$(date +%s)
