name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      working-directory: ./banking-service/src/main/docker
      run: docker build . --file Dockerfile --tag banking-service:$(date +%s)
